# Generated by Django 4.0.2 on 2022-10-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessusers',
            old_name='ip_address',
            new_name='ip_correo',
        ),
    ]
