# Generated by Django 4.0.2 on 2022-10-13 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Número de cedula')),
                ('correo', models.CharField(blank=True, default='@elsistema.org.ve', max_length=150, null=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=13, verbose_name='Ruc')),
                ('correo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('mobile', models.CharField(max_length=20, verbose_name='Teléfono Celular')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono Convencional')),
                ('website', models.CharField(max_length=150, verbose_name='Website')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
                'ordering': ['id'],
                'permissions': (('change_company', 'Can change Company'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d', verbose_name='Imagen')),
                ('is_inventoried', models.BooleanField(default=True, verbose_name='¿Es inventariado?')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('serial', models.CharField(max_length=45, verbose_name='Serial del Producto')),
                ('serial_inventario', models.CharField(max_length=45, verbose_name='Serial de Inventario del Producto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('serial', models.CharField(max_length=45, verbose_name='Serial del Producto')),
                ('serial_inventario', models.CharField(max_length=45, verbose_name='Serial de Inventario del Producto')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.company')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sale')),
            ],
            options={
                'verbose_name': 'Detalle de Salida',
                'verbose_name_plural': 'Detalle de Salidas',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
