# Generated by Django 4.0.2 on 2022-10-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ruc',
        ),
        migrations.AddField(
            model_name='company',
            name='rif',
            field=models.CharField(default=0, max_length=13, verbose_name='rif'),
            preserve_default=False,
        ),
    ]
